# Generated by Django 5.0 on 2024-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_password_register_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLogins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default='g@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logins',
            name='email',
            field=models.EmailField(default='gokul', max_length=254),
            preserve_default=False,
        ),
    ]
